apiVersion: v1
kind: Pod
metadata:
  name: pod-nodeaffinity
  labels:
    app: nginxserver
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: disksize
            operator: In
            values:
            - small
            - medium
  containers:
  - name:  nginx-container
    image: nginx
    ports:
      - containerPort: 80