---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    app: my-app
spec:
  replicas: {{.Values.replicas }}
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: hello
        image: {{.Values.hello.image}}:{{.Values.version}}
        ports:
        - containerPort: 8080
