apiVersion: v1
kind: Pod
metadata:
  name: my-pod-secret
spec:
  containers:
    - name: budybox-container
      image: busybox
      command: [ "/bin/sh", "-c", "env" ]
      env: 
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: password
      envFrom:
      - secretRef:
          name: my-secret      
  restartPolicy: Never
  