apiVersion: v1
kind: Pod
metadata:
  name: my-nginx-pod
  namespace: dev
  labels:
    app: nginxserver
spec:
  containers:
  - name:  nginx-container
    image: nginx
    ports:
      - containerPort: 80
      