apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment-nopdb
  labels:
    app: my-app-deployment-nopdb
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app-nopdb
  template:
    metadata:
      labels:
        app: my-app-nopdb
    spec:
      containers:
      - name:  nginx-container
        image: nginx
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 90 # READYになるまで約90秒かかるようにする
        
