apiVersion: v1
kind: Service
metadata:
  name: xray-demoapp-service
  namespace: xray
  labels:
    app: xray-demoapp-service
spec:
  selector:
    app: python-web-xray
  type: LoadBalancer
  ports:
   -  protocol: TCP
      port: 80
      targetPort: 8000
