apiVersion: apps/v1
kind: Deployment
metadata:
  name: xray-demoapp-deployment
  namespace: xray
  labels:
    app: xray-demoapp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-web-xray
  template:
    metadata:
      labels:
        app: python-web-xray
    spec:
      serviceAccountName: xray-demoapp-sa
      containers:
      - name:  python-web-xray
        image: tnobe/python-web-xray
        ports:
        - containerPort: 8000
        env:
        - name: AWS_XRAY_DAEMON_ADDRESS
          value: xray-service.xray:2000
        - name: REGION
          value: ap-northeast-1
        - name: QUEUE_NAME
          value: Demo-XRay-Q
        
