apiVersion: v1
kind: Pod
metadata:
  name: gold-pod
  namespace: prod
  labels:
    app:   webserver
    stack: gold
spec:
  containers:
  - name:  nginx-container
    image: nginx
    ports:
      - containerPort: 80
  nodeSelector:
    stack: gold