apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels:
    app: my-app
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  selector:
    app: my-app
  type: LoadBalancer
  ports:
   -  protocol: TCP
      port: 80
      targetPort: 8080

