version: 0.2
env:
  variables:
    EKS_CLUSTER_NAME: "lab2-cluster"
    KUBECTL_ROLE_ARN: "arn:aws:iam::000000000000:role/my-Role"
phases:
  install:
    commands:
      - yum install -y awscli git python3 jq gettext bash-completion moreutils
      - curl -sSL https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
      - helm version --short
  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - aws --version
      - CREDENTIALS=$(aws sts assume-role --role-arn $KUBECTL_ROLE_ARN --role-session-name codebuild-kubectl --duration-seconds 900)
      - export AWS_ACCESS_KEY_ID="$(echo ${CREDENTIALS} | jq -r '.Credentials.AccessKeyId')"
      - export AWS_SECRET_ACCESS_KEY="$(echo ${CREDENTIALS} | jq -r '.Credentials.SecretAccessKey')"
      - export AWS_SESSION_TOKEN="$(echo ${CREDENTIALS} | jq -r '.Credentials.SessionToken')"
      - export AWS_EXPIRATION=$(echo ${CREDENTIALS} | jq -r '.Credentials.Expiration')
      - aws eks update-kubeconfig --name $EKS_CLUSTER_NAME
  build:
    commands:
      - echo Entered the build phase...
      - helm upgrade -i hello-app ./
  post_build:
    commands:
      - echo Entered the post_build phase...
      - helm status hello-app
