apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: NodePort
  selector:
    app: webserver-deployment
  port:
    - nodePort: 30000
      protocol: TCP
      port: 8080
      targetPort: 80