apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: default
  labels:
    app: my-service
spec:
  selector:
    app: python-web-xray
  type: LoadBalancer
  ports:
   -  protocol: TCP
      port: 80
      targetPort: 8000
