apiVersion: v1
kind: Service
metadata:
  name: my-service-loadbalancer
  namespace: student99
spec:
  type: LoadBalancer 
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: python-web-ec2
