apiVersion: v1
kind: Service
metadata:
  name: my-service-nodeport
  namespace: student99
spec:
  type: NodePort 
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8000
    # nodePort: 30000
  selector:
    app: python-web-ec2
