apiVersion: v1
kind: Pod
metadata:
  name: my-shell
  labels:
    app: my-shell
spec:
  serviceAccountName: aws-s3-read
  containers:
  - name:  aws-cli-container
    image: amazon/aws-cli
    command:
    - sleep
    - "9999"
